# Generated by Django 4.1.5 on 2023-01-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.CharField(choices=[('grocery', 'grocery'), ('houserent', 'houserent'), ('outing', 'outing'), ('travel', 'travel'), ('service', 'service')], default='service', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='no_of_persons',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='budget',
            name='user_id',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
